extraction:
  cpp:
    after_prepare: 
      - python report.py 21
  cobol:
    after_prepare: 
      - python report.py 21
  csharp:
    after_prepare: 
      - python report.py 21
  java:
    after_prepare: 
      - python report.py 21
  javascript:
    after_prepare: 
      - python report.py 21
  python:
    after_prepare: 
      - python report.py 21
